class Collections:
    STUDENT = 'Student'
    EMPLOYEE = 'Employee'
    ASSIGNMENT = 'Assignment'
    CLASSROOM = 'Classroom'
    CLASSES = 'Classes'
    SUBJECT = 'Subject'
    STUDENT_GROUP = 'Student_group'
    SUBJECT_GROUP = 'Subject_group'
    SYLLABUS = 'Syllabus'
    FIELD = 'Field'
